### ISSUE TITLE
On Fedora 43 himmelblaud cache folder is inaccessable, failing deamon

### ISSUE THREAD

**Issue by Jimmy89** [himmelblau-idm/himmelblau#913]
**Description**
I installed all himmelblau tools through the rpm repo on a completely freshly installed Fedora 43 workstation. I followed the documentation to setup himmelblau.
Currently, the himmelblau deamon does not start. Starting it with debug mode display the message: "Refusing to run, DB folder /var/cache/himmelblaud does not exists".

**Steps to Reproduce**
1. Install himmelblau through rpm repo on fedora 43 (`sudo dnf install -y himmelblau pam-himmelblau nss-himmelblau himmelblau-sshd-config himmelblau-qr-greeter himmelblau-sso o365 himmelblau-selinux`).
2. Setup global domain and try to start/debug the himmelblau service.

**Logs**
``` 
6477be23-f5dc-4402-9f41-47d7c82458e0 INFO     initialisation [ 58.0µs | 100.00% ]
6477be23-f5dc-4402-9f41-47d7c82458e0 DEBUG    ┝━ 🐛 [debug]: 🧹 Cleaning up sockets from previous invocations
6477be23-f5dc-4402-9f41-47d7c82458e0 DEBUG    ┝━ 🐛 [debug]: Path "/var/run/himmelblaud/socket" doesn't exist, not attempting to remove.
6477be23-f5dc-4402-9f41-47d7c82458e0 DEBUG    ┝━ 🐛 [debug]: Path "/var/run/himmelblaud/task_sock" doesn't exist, not attempting to remove.
6477be23-f5dc-4402-9f41-47d7c82458e0 DEBUG    ┝━ 🐛 [debug]: Path "/var/run/himmelblaud/broker_sock" doesn't exist, not attempting to remove.
6477be23-f5dc-4402-9f41-47d7c82458e0 ERROR    ┝━ 🚨 [error]: Refusing to run, DB folder /var/cache/himmelblaud does not exist
6477be23-f5dc-4402-9f41-47d7c82458e0 INFO     ┕━ ｉ [info]:  | diag: -- diagnosis for path: /var/cache/himmelblaud/himmelblau.cache.db
unable to canonicalise path
running as: 1000:1000
path permissions

  /                                          : DIR access: true owner: 0 group: 0 mode: r-xr-xr-x
  /var                                       : DIR access: true owner: 0 group: 0 mode: rwxr-xr-x
  /var/cache                                 : DIR access: true owner: 0 group: 0 mode: rwxr-xr-x
  /var/cache/himmelblaud                     : ERROR: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
  /var/cache/himmelblaud/himmelblau.cache.db : ERROR: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

  note that accessibility does not account for ACL's or MAC
-- end diagnosis
```

```
LS output ( ls -l /var/cache/)
lrwxrwxrwx. 1 root   root    19 Dec  3 16:31 himmelblaud -> private/himmelblaud
```

```
ls -l /var/cache/private/
total 0
drwxr-xr-x. 1 nobody nobody 0 Dec  3 16:31 himmelblaud

```

The cache folder belongs to nobody. That does not seem good.

**Comment by dmulder** [comment]
That's a path created by systemd, for the DynamicUser `himmelblaud`. So, it's rather odd that it's failing to start, because it neglected to create it's own directories?

**Comment by dmulder** [comment]
Granted, I was just mucking with these directory creations to resolve some issues with Fedora 43 Silverblue. Perhaps the tmpfile systemd directory creations have broken the DynamicUser directory flow?

**Comment by Jimmy89** [comment]
It looks like this commit should fix the problem:
https://github.com/himmelblau-idm/himmelblau/commit/36e218a347e08fa5641d032e08fd4ff603d09efb

Update: wait this if for /var/lib. But the problem seems the same.

**Comment by dmulder** [comment]
Which is actually ready to merge: https://github.com/himmelblau-idm/himmelblau/pull/914

**Comment by Jimmy89** [comment]
I was too quick with typing. It's in a different dir (/var/lib) and not /var/cache. Could it be that this is the same problem but on a different line?

**Comment by dmulder** [comment]
No, that fix was specifically about creating directories that are used during the post install script.

**Comment by dmulder** [comment]
Could you re-test this on Himmelblau 2.1.0? I ran this without problems on Fedora 43 Workstation yesterday. The only lingering issue that I encountered was that selinux has to be set to not enforce (apparently we are still missing some entries).

**Comment by Jimmy89** [comment]
@dmulder I did not notice your message. I will test this upcoming Monday (22th) and I will let you know the result.

**Comment by carlesgs** [comment]
Hello,

Try changing the selinux mode to **disabled** or **permissive** in **/etc/selinux/config**. Restart the Linux client and try again.

In the current state of your installation, you may not be able to get it to work because you are missing the **/var/cache/himmelblaud** directory and probably also **/var/run/himmelblaud**. 

If changing the selinux mode does not work, you will have to uninstall the packages and start the himmelblau installation process on Fedora again, changing the selinux mode as I mentioned.

Let us know if it worked for you. More information here: https://github.com/himmelblau-idm/himmelblau/issues/919#issuecomment-3700149572

**Comment by Jimmy89** [comment]
@carlesgs @dmulder I tested it out, by first setting selinux to `permissive`, rebooted the linux client, then removing all himmelblaud (dnf remove) packages and then re-installing them.
I noticed that the /var/cache/himmelblaud directory (actually /var/cache/private/himmelblaud/) was still having the incorrect permissions, so I removed all himmelblaud packages again, manually removed the /var/cache/private and symbolic link /var/cache/himmelblaud directory. Then I installed the ` himmelblau pam-himmelblau nss-himmelblau o365 himmelblau-sso`  packages again.

Result: 
 - The `/etc/himmelblau/himmelblau.conf ` is overwritten with the default file. I hope this does not happen with upgrades, as that would create an unstable system.
 - The `/var/cache/himmelblaud`  directory is not re-created. I get

```
09391853-352f-475b-b862-a46fda6463bc DEBUG    ┝━ 🐛 [debug]: Path "/var/run/himmelblaud/socket" doesn't exist, not attempting to remove.
09391853-352f-475b-b862-a46fda6463bc DEBUG    ┝━ 🐛 [debug]: Path "/var/run/himmelblaud/task_sock" doesn't exist, not attempting to remove.
09391853-352f-475b-b862-a46fda6463bc DEBUG    ┝━ 🐛 [debug]: Path "/var/run/himmelblaud/broker_sock" doesn't exist, not attempting to remove.
09391853-352f-475b-b862-a46fda6463bc ERROR    ┝━ 🚨 [error]: Refusing to run, DB folder /var/cache/himmelblaud does not exist
09391853-352f-475b-b862-a46fda6463bc INFO     ┕━ ｉ [info]:  | diag: -- diagnosis for path: /var/cache/himmelblaud/himmelblau.cache.db
unable to canonicalise path
running as: 1000:1000
path permissions

  /                                          : DIR access: true owner: 0 group: 0 mode: r-xr-xr-x
  /var                                       : DIR access: true owner: 0 group: 0 mode: rwxr-xr-x
  /var/cache                                 : DIR access: true owner: 0 group: 0 mode: rwxr-xr-x
  /var/cache/himmelblaud                     : ERROR: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  /var/cache/himmelblaud/himmelblau.cache.db : ERROR: Os { code: 2, kind: NotFound, message: "No such file or directory" }
``` 

Not sure why I does not re-create this specific folder with cache file. I do see other himmelblaud folders now.

```
ls -l /var/cache/
drw-------. 1 root   root     0 Dec 30 11:32 himmelblau-policies
drwxr-xr-x. 1 root   root    16 Jan  4 18:31 nss-himmelblau
drwx------. 1 root   root     0 Jan  4 18:44 private
```

The private folder does not contain the himmelblaud cache dir and the symbol link is not created either.

I also note the difference in access rights between the himmelblau-policies and nss-himmelblau folders.

**Comment by klaus4040** [comment]
Maybe I should have made a new issue, but since in the same distro family with selinux issues were mentioned and probably the issue here:

Installing the selinux rpm fails on Rocky 10 and RHEL10 (my 2 test machines) when it installs the policies.

semodule -i /usr/share/selinux/packages/himmelblaud.pp
Failed to resolve typeattributeset statement at /var/lib/selinux/targeted/tmp/modules/400/himmelblaud/cil:56
Failed to resolve AST
semodule:  Failed!

This is with version 2.3.1.
With this selinux will always fail obviously.

I have not enough knowledge about selinux to help with code but I can run tests if needed.

Here is a log with more verbose output if it helps.

[himmelblau-selinuxinstall.log](https://github.com/user-attachments/files/24680341/himmelblau-selinuxinstall.log)
